//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GioHang
    {
        public int Id { get; set; }
        public int IdKhachHang { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    }
}
