//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GioHang_SanPham
    {
        public int Id { get; set; }
        public int IdSanPham { get; set; }
        public int IdGioHang { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public Nullable<int> IsDelete { get; set; }
    }
}
