//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DatHang
    {
        public System.Guid Id { get; set; }
        public int IdGioHang { get; set; }
        public int IdKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public Nullable<decimal> TongHoaDon { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> NgayXacNhan { get; set; }
        public bool IsDelete { get; set; }
    }
}
